name: Test Workflow
on:
  workflow_dispatch:
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      env: 
        VAR1: 98.4342334
      run: echo "${{env.VAR1}}."
    
