name: Test Workflow
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      env: 
        VAR1: 98.4342334
      run: echo "${{VAR1}}."
    
