name: Test Workflow
on:
  workflow_dispatch:
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      env: 
        VAR1: 98.4342334
      run: |
        rounded=$(printf "%.2f" $VAR1)
        echo $rounded
    
